language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "pypy"

install:
  - pip install -r requirements-test.txt
  - pip install coveralls
  - pip install .

script: nosetests -v --with-coverage --cover-package=pyjsonrpc
after_success: coveralls $COVERALLS_OPTION
